services:
  chatapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: multi-room-chat
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge